version: "3"
services:
  shepherd:
    image: containrrr/shepherd:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - SLEEP_TIME=1440m
    deploy:
      placement:
        constraints:
          - node.role == manager
