version: "3.2"

services:
  nfs_service:
    image: busybox
    command: mktemp /data/test-file.XXXXXX
    volumes:
      - type: volume
        source: nfs_volume
        target: /data
        volume:
          nocopy: true
    environment:
      TZ: ${TIME_ZONE:-America/Sao_Paulo}
    deploy:
      mode: global

volumes:
  nfs_volume:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=${NFS_IP?Variable not set},nolock,soft,rw
      device: ":${NFS_SHARE_PATH?Variable not set}"
